### ISSUE TITLE
Keyboard Feedback

### ISSUE THREAD

**Issue by mckayfackrell** [alombi/ios-settings-urls-website#1]
I can’t seem to find one for Settings > Sounds & Haptics > Keyboard Feedback

Edit: I asked ChatGPT (and after a couple incorrect ones) it gave me the working url scheme

Prefs:root=Sounds&path=Keyboard%20Feedback

**Comment by urbanvietcong** [comment]
Great! 

This website only shows the list of URLs that are contained in another [repo](https://github.com/FifiTheBulldog/ios-settings-urls) maintained by [FifiTheBulldog](https://github.com/FifiTheBulldog); so if you find a new URL you may want to add it there :)
